#!/usr/bin/env bash
#last tested with: bash 5.2.x

# Copyright 2023 Dr. Juan Miguel Cejuela


#
# Download arXiv PDF article with a sensible filename format:
# `PUBLICATION_ISO_DATE (UPDATED_ISO_DATE vX) - AUTHORS_SHORTENED - TITLE.pdf`
#
# `(UPDATED_ISO_DATE vX)`` is optional and only written if the article was updated; `vX` is the latest update version number (if any, i.e., `X` >= 2).
#
# Arguments:
# 1: article's URL or identifier
# 2: (OPTIONAL) folder to save the PDF into (it defaults to the current directory).
#
arxiv_download_PDF() {
  article="$1"
  save_to="${2-"."}"

  # Check if input is a URL or an identifier
  if [[ "$article" =~ ^https?://arxiv.org/abs/(.+)$ ]]; then
    identifier="${BASH_REMATCH[1]}"
  elif [[ -z "$article" ]]; then
    echo >&2 "Error: Empty arXiv URL or identifier"
    exit 1
  else
    identifier="$article"
  fi

  # Get the metadata for the article
  metadata=$(curl -sLH "Accept: application/json" "http://export.arxiv.org/api/query?id_list=$identifier")

  # Check if the API returned an error
  if [[ $metadata == *"<title>Error</title>"* ]]; then
    echo >&2 "Error: Invalid arXiv URL or identifier: ${identifier}"
    exit 1
  fi

  # Extract the relevant information from the metadata using xpath (requires xmllint)
  original_date=$(echo "$metadata" | xmllint --xpath '//*[local-name()="entry"]/*[local-name()="published"]/text()' -)
  latest_date=$(echo "$metadata" | xmllint --xpath '//*[local-name()="entry"]/*[local-name()="updated"]/text()' -)
  title=$(echo "$metadata" | xmllint --xpath '//*[local-name()="entry"]/*[local-name()="title"]/text()' -)
  authors=$(echo "$metadata" | xmllint --xpath '//*[local-name()="entry"]//*[local-name()="author"]/*[local-name()="name"]/text()' - | awk '{print $NF}' | paste -sd "," -)
  latest_version=$(echo "$metadata" | xmllint --xpath '//*[local-name()="entry"]/*[local-name()="id"]/text()' - | grep -oE 'v[0-9]+' | tr -d 'v')

  # Format the dates by extracting the first 10 characters (date in ISO format)
  original_date=${original_date:0:10}
  latest_date=${latest_date:0:10}

  # Shorten the authors names according to the rules
  IFS=',' read -ra authors_array <<<"$authors"
  if [ "${#authors_array[@]}" -ge 4 ]; then
    authors="${authors_array[0]} et al"
  fi

  # Construct the filename according to the format
  filename="$original_date"
  if [ "$latest_version" != "1" ]; then
    filename+=" ($latest_date v$latest_version)"
  fi
  filename+=" - $authors - $(_escape_str_for_filename "$title").pdf"

  out_filepath="$save_to/$filename"

  # Download the PDF
  curl -sS "https://arxiv.org/pdf/$identifier.pdf" --output "$out_filepath"

  echo "Downloaded PDF as: $out_filepath"
}


_escape_str_for_filename() {
  _x="$1"
  _x="${_x//\// }"
  _x="${_x//:/;}"
  # NOTE: we echo without double quotes. In this way, bash collapses contiguous whitespaces
  echo $_x
}


if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  arxiv_download_PDF "$@"
fi
